from .config import (MORSE_CODE_EN_CODE, MORSE_CODE_NUMBERS_CODE, MORSE_CODE_RU_CODE, MORSE_CODE_EN_LANGUAGE,
                     MORSE_CODE_NUMBERS_LANGUAGE, MORSE_CODE_RU_LANGUAGE, MORSE_CODES_DICT, MORSE_CODE_SYMBOLS_CODE)
from .dechifrator import MorseTranslator
